---
- hosts: localhost
  
  tasks:
    - name: Get Organization Networks
      cisco.meraki.networks_info:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
      register: result
      
    - name: Filter networks with "wireless" productTypes
      set_fact:
        filtered_networks: "{{ result.meraki_response | selectattr('productTypes', 'contains', 'camera') | list }}"
      register: network_id_get

    - name: Meraki-Demo-Camera-Profile
      cisco.meraki.devices_camera_wireless_profiles:
        meraki_api_key: "{{ meraki_key }}"
        state: present
        serial: "{{ camera_serial }}"
        ids:
          backup: 'Demo-RF-Profile'
          primary: 'Demo-RF-Profile'
          secondary: 'Demo-RF-Profile'

    - name: Meraki-Demo-Quality-Profile
      cisco.meraki.devices_camera_quality_and_retention:
        meraki_api_key: "{{ meraki_key }}"
        state: present
        audioRecordingEnabled: false
        motionBasedRetentionEnabled: false
        motionDetectorVersion: 2
        serial: "{{ camera_serial }}"
        profileId: '1234'
        quality: Standard
        resolution: 1280x720
        restrictedBandwidthModeEnabled: false
