---
- name: meraki deployment
  hosts: localhost
  vars:
    auth_key: "{{ meraki_key }}"
    org_name: "{{ org_name }}"

  tasks:

    - name: include variables for devices
      include_vars:
        file: devices.yaml
        name: devices

    - name: include variables for addresses
      include_vars:
        file: addresses.yaml
        name: addresses

    - name: Create site network
      cisco.meraki.meraki_network:
        auth_key: "{{ auth_key }}"
        state: present
        org_name: "{{ org_name }}"
        name: "{{ item.value.network_name }}"
        type:
          - switch
          - appliance
          - wireless
      register: off_network
      loop: "{{ lookup('dict', devices, wantlist=True) }}"
      when: "'device-1' in item.key"

    - name: Add devices to Network
      cisco.meraki.meraki_device:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        net_id: "{{ off_network.results.0.data.id }}"
        state: present
        serial: "{{ item.value.serial_no }}"
      register: off_add_dev1
      loop: "{{ lookup('dict', devices, wantlist=True) }}"

    - name: Update device Information
      cisco.meraki.meraki_device:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        net_id: "{{ off_network.results.0.data.id }}"
        state: present
        serial: "{{ item.value.serial_no }}"
        name: " {{ item.value.device_name }}"
        move_map_marker: no
      register: off_update_dev1
      loop: "{{ lookup('dict', devices, wantlist=True) }}"


    - name: Bind a template from a network
      cisco.meraki.meraki_config_template:
        auth_key: "{{ auth_key }}"
        state: present
        org_name: "{{ org_name }}"
        net_name: "{{ item.value.network_name }}"
        config_template: "{{ item.value.template_name }}"
      delegate_to: localhost
      loop: "{{ lookup('dict', devices, wantlist=True) }}"
      when: "'device-1' in item.key"

    - name: Add subnets
      cisco.meraki.networks_appliance_vlans:
        meraki_api_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        net_id: "{{ off_network.results.0.data.id }}"
        state: present
        name: "{{ item.value.name }}"
        vlanId: "{{ item.value.vlan_id }}"
        subnet: "{{ item.value.subnet }}"
        applianceIp: "{{ item.value.default_gw }}"
      loop: "{{ lookup('dict', addresses) }}"
