---
- hosts: localhost
  
  tasks:
    - name: Get Organization Networks
      cisco.meraki.networks_info:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
      register: result
      
    - name: Filter networks with "appliance" productTypes
      set_fact:
        filtered_networks: "{{ result.meraki_response | selectattr('productTypes', 'contains', 'appliance') | list }}"
      register: network_id_get
      
    - name: Update allowed IPs for ICMP
      cisco.meraki.networks_appliance_firewall_firewalled_services:
        meraki_api_key: "{{ meraki_key }}"
        state: present
        access: restricted
        allowedIps:
        - 10.123.123.10
        - 10.123.123.13
        networkId: "{{ filtered_networks.0.id }}"
        service: ICMP

    - name: Update L3 rules
      cisco.meraki.networks_appliance_firewall_l3_firewall_rules:
        meraki_api_key: "{{ meraki_key }}"
        state: present
        networkId: "{{ filtered_networks.0.id }}"
        rules:
        - comment: Deny Traffic to 4.2.2.2
          destCidr: 4.2.2.2
          destPort: Any
          policy: deny
          protocol: Any
          srcCidr: Any
          srcPort: Any
          syslogEnabled: false

    - name: Update L7 rules
      cisco.meraki.networks_appliance_firewall_l7_firewall_rules:
        meraki_api_key: "{{ meraki_key }}"
        state: present
        networkId: "{{ filtered_networks.0.id }}"
        rules:
        - policy: deny
          type: host
          value: google.com
        - policy: deny
          type: port
          value: '23'
        - policy: deny
          type: ipRange
          value: 10.11.12.00/24
