---
- hosts: localhost

  vars_files:
    - meraki_wifi_vars.yml
  
  tasks:
    - name: Get Organization Networks
      cisco.meraki.networks_info:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
      register: result
      
    - name: Filter networks with "wireless" productTypes
      set_fact:
        filtered_networks: "{{ result.meraki_response | selectattr('productTypes', 'contains', 'wireless') | list }}"
      register: network_id_get

    - debug:
        msg:
        - "Print network_id_get '{{ network_id_get.ansible_facts.filtered_networks.0.id }}'"
     
    - name: Edit SSID Settings
      cisco.meraki.networks_wireless_ssids: 
        meraki_api_key: "{{ meraki_key }}"
        networkId: "{{ network_id_get.ansible_facts.filtered_networks.0.id }}"
        enabled: "{{ item.enabled }}"
        state: "{{ item.state | default('present') }}"
        name: "{{ item.name }}"
        number: "{{ item.number }}"
        encryptionMode: "{{ item.authentication.encryption_mode }}"
        authMode: "{{ item.authentication.auth_mode }}"
        psk: "{{ item.authentication.psk }}"
        wpaEncryptionMode: "{{ item.authentication.wpa_encryption_mode }}"
      delegate_to: localhost
      loop: "{{ SSID }}"
      loop_control: 
        label: "{{ filtered_networks.id }}"
